In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split

,Customer ID,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,7590-VHVEA,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7039,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7040,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7041,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7042,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7043,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [12]:
data=pd.read_csv('data/Churn.csv')
data
X = pd.get_dummies(data.drop(['Churn', 'Customer ID'], axis=1))
y = data['Churn'].apply(lambda x: 1 if x=='Yes' else 0)

In [9]:
X

,Senior Citizen,tenure,Monthly Charges,Gender_Female,Gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,Phone Service_No,...,Total Charges_995.35,Total Charges_996.45,Total Charges_996.85,Total Charges_996.95,Total Charges_997.65,Total Charges_997.75,Total Charges_998.1,Total Charges_999.45,Total Charges_999.8,Total Charges_999.9
0,0,1,29.85,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,1,29.85,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,34,56.95,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,2,53.85,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,45,42.30,0,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7039,0,24,84.80,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7040,0,72,103.20,1,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7041,0,11,29.60,1,0,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7042,1,4,74.40,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7043,0,66,105.65,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [22]:
#import keras dependencies
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [25]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_dim=len(X_train.columns)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics='accuracy')

In [27]:
model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
177/177 [==============================] - 1s 4ms/step - loss: 0.4412 - accuracy: 0.7897
Epoch 2/10
177/177 [==============================] - 1s 5ms/step - loss: 0.4380 - accuracy: 0.7947
Epoch 3/10
177/177 [==============================] - 1s 5ms/step - loss: 0.4451 - accuracy: 0.7888
Epoch 4/10
177/177 [==============================] - 1s 4ms/step - loss: 0.4414 - accuracy: 0.7894: 0s - loss: 0
Epoch 5/10
177/177 [==============================] - 1s 3ms/step - loss: 0.4405 - accuracy: 0.7894
Epoch 6/10
177/177 [==============================] - 1s 3ms/step - loss: 0.4387 - accuracy: 0.7917
Epoch 7/10
177/177 [==============================] - 1s 3ms/step - loss: 0.4378 - accuracy: 0.7901
Epoch 8/10
177/177 [==============================] - 1s 3ms/step - loss: 0.4375 - accuracy: 0.7902
Epoch 9/10
177/177 [==============================] - 1s 3ms/step - loss: 0.4358 - accuracy: 0.7890
Epoch 10/10
177/177 [==============================] - 1s 4ms/step - loss: 0.4324 - accuracy: 0.7973

In [30]:
y_hat = model.predict(X_test)
y_hat = [0 if val < 0.5 else 1 for val in y_hat]