In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split

,Customer ID,Gender,Senior Citizen,Partner,Dependents,tenure,Phone Service,Multiple Lines,Internet Service,Online Security,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,7590-VHVEA,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
2,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
3,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7039,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7040,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7041,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7042,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7043,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [12]:
data=pd.read_csv('data/Churn.csv')
data
X = pd.get_dummies(data.drop(['Churn', 'Customer ID'], axis=1))
y = data['Churn'].apply(lambda x: 1 if x=='Yes' else 0)

In [9]:
X

,Senior Citizen,tenure,Monthly Charges,Gender_Female,Gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,Phone Service_No,...,Total Charges_995.35,Total Charges_996.45,Total Charges_996.85,Total Charges_996.95,Total Charges_997.65,Total Charges_997.75,Total Charges_998.1,Total Charges_999.45,Total Charges_999.8,Total Charges_999.9
0,0,1,29.85,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,1,29.85,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,34,56.95,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,2,53.85,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,45,42.30,0,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7039,0,24,84.80,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7040,0,72,103.20,1,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7041,0,11,29.60,1,0,0,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7042,1,4,74.40,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7043,0,66,105.65,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [22]:
#import keras dependencies
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [ ]:
#base line model
model = Sequential()
model.add(Dense(units=32, activation='relu', input_dim=len(X_train.columns)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

In [48]:
#updates model
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras import regularizers

# Create a new sequential model
model = Sequential()

# Add a dense layer with regularization and batch normalization
model.add(Dense(units=128, activation='relu', input_dim=len(X_train.columns),
                kernel_regularizer=regularizers.l2(0.01)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Add more dense layers
model.add(Dense(units=64, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(units=32, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Add the final dense layer with sigmoid activation
model.add(Dense(units=16, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Add the final dense layer with sigmoid activation
model.add(Dense(units=8, activation='relu', kernel_regularizer=regularizers.l2(0.01)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Add the final dense layer with sigmoid activation
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [49]:
model.fit(X_train, y_train, epochs=30, batch_size=32)

Epoch 1/30
177/177 [==============================] - 5s 13ms/step - loss: 2.1084 - accuracy: 0.6662
Epoch 2/30
177/177 [==============================] - 2s 12ms/step - loss: 1.4919 - accuracy: 0.7430
Epoch 3/30
177/177 [==============================] - 2s 13ms/step - loss: 1.2144 - accuracy: 0.7597
Epoch 4/30
177/177 [==============================] - 2s 12ms/step - loss: 1.0433 - accuracy: 0.7686
Epoch 5/30
177/177 [==============================] - 2s 14ms/step - loss: 0.9099 - accuracy: 0.7693
Epoch 6/30
177/177 [==============================] - 2s 13ms/step - loss: 0.8108 - accuracy: 0.7805
Epoch 7/30
177/177 [==============================] - 2s 12ms/step - loss: 0.7343 - accuracy: 0.7915
Epoch 8/30
177/177 [==============================] - 2s 12ms/step - loss: 0.6869 - accuracy: 0.7723
Epoch 9/30
177/177 [==============================] - 2s 12ms/step - loss: 0.6437 - accuracy: 0.7842
Epoch 10/30
177/177 [==============================] - 2s 12ms/step - loss: 0.6035 - accuracy: 0.7917
Epoch 11/30
177/177 [==============================] - 2s 13ms/step - loss: 0.5802 - accuracy: 0.7885
Epoch 12/30
177/177 [==============================] - 2s 14ms/step - loss: 0.5627 - accuracy: 0.7897
Epoch 13/30
177/177 [==============================] - 3s 14ms/step - loss: 0.5511 - accuracy: 0.7842
Epoch 14/30
177/177 [==============================] - 2s 13ms/step - loss: 0.5310 - accuracy: 0.7945
Epoch 15/30
177/177 [==============================] - 2s 12ms/step - loss: 0.5339 - accuracy: 0.7805
Epoch 16/30
177/177 [==============================] - 2s 12ms/step - loss: 0.5160 - accuracy: 0.7940
Epoch 17/30
177/177 [==============================] - 2s 13ms/step - loss: 0.5031 - accuracy: 0.7913
Epoch 18/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4951 - accuracy: 0.7941
Epoch 19/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4935 - accuracy: 0.7863
Epoch 20/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4879 - accuracy: 0.7954
Epoch 21/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4887 - accuracy: 0.7936
Epoch 22/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4770 - accuracy: 0.7952
Epoch 23/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4791 - accuracy: 0.7879
Epoch 24/30
177/177 [==============================] - 2s 14ms/step - loss: 0.4708 - accuracy: 0.7966
Epoch 25/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4709 - accuracy: 0.7961
Epoch 26/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4704 - accuracy: 0.7902
Epoch 27/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4689 - accuracy: 0.7918
Epoch 28/30
177/177 [==============================] - 2s 13ms/step - loss: 0.4707 - accuracy: 0.7881
Epoch 29/30
177/177 [==============================] - 2s 12ms/step - loss: 0.4625 - accuracy: 0.7899
Epoch 30/30
177/177 [==============================] - 2s 12ms/step - loss: 0.4668 - accuracy: 0.7874

In [40]:
y_hat = model.predict(X_test)
y_hat = [0 if val < 0.5 else 1 for val in y_hat]

In [41]:
model.save('tfmodel')
del model 
model = load_model('tfmodel')

INFO:tensorflow:Assets written to: tfmodel\assets

In [50]:
y_hat = model.predict(X_test)
y_hat = [0 if val < 0.5 else 1 for val in y_hat]
accuracy_score(y_test, y_hat)

0.7828246983676366